# Generated by Django 4.1.5 on 2023-01-30 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
                ('model', models.CharField(max_length=300)),
                ('super_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supers.super')),
            ],
        ),
    ]
