# Generated by Django 4.1.5 on 2023-01-31 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='super',
            name='alter_ego',
            field=models.CharField(default='', max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='super',
            name='catchphrase',
            field=models.CharField(default='', max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='super',
            name='primary_ability',
            field=models.CharField(default='', max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='super',
            name='secondary_ability',
            field=models.CharField(default='', max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='super',
            name='super_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='super_types.supertype'),
            preserve_default=False,
        ),
    ]
